const classs = [
  {
    name: "Bárbaro",
    hitDie: "d12",
    primaryAbility: "Fuerza",
    weapons: "Armas simples y marciales",
    savingThrows: ["Fuerza", "Constitución"],
    features: ["Rabia", "Defensa sin armadura"],
  },
  {
    name: "Bardo",
    hitDie: "d8",
    primaryAbility: "Carisma",
    weapons:
      "Armas simples, ballesta de mano, espada larga, estoque, espada corta",
    savingThrows: ["Destreza", "Carisma"],
    features: ["Inspiración bárdica", "Lanzamiento de conjuros"],
  },
  {
    name: "Clérigo",
    hitDie: "d8",
    primaryAbility: "Sabiduría",
    weapons: "Armas simples",
    savingThrows: ["Sabiduría", "Carisma"],
    features: ["Magia divina", "Canalizar divinidad"],
  },
  {
    name: "Druida",
    hitDie: "d8",
    primaryAbility: "Sabiduría",
    weapons:
      "Armas simples, además de guadañas, hondas, bastones y lanzas (no usan metal)",
    savingThrows: ["Inteligencia", "Sabiduría"],
    features: ["Forma salvaje", "Lanzamiento de conjuros"],
  },
  {
    name: "Guerrero",
    hitDie: "d10",
    primaryAbility: "Fuerza o Destreza",
    weapons: "Todas las armas simples y marciales",
    savingThrows: ["Fuerza", "Constitución"],
    features: ["Ataque adicional", "Estilo de combate"],
  },
  {
    name: "Monje",
    hitDie: "d8",
    primaryAbility: "Destreza y Sabiduría",
    weapons: "Armas simples, además de espadas cortas",
    savingThrows: ["Fuerza", "Destreza"],
    features: ["Artes marciales", "Defensa sin armadura"],
  },
  {
    name: "Paladín",
    hitDie: "d10",
    primaryAbility: "Fuerza y Carisma",
    weapons: "Todas las armas simples y marciales",
    savingThrows: ["Sabiduría", "Carisma"],
    features: ["Imposición de manos", "Castigo divino"],
  },
  {
    name: "Explorador",
    hitDie: "d10",
    primaryAbility: "Destreza y Sabiduría",
    weapons: "Todas las armas simples y marciales",
    savingThrows: ["Fuerza", "Destreza"],
    features: ["Enemigo predilecto", "Explorador natural"],
  },
  {
    name: "Pícaro",
    hitDie: "d8",
    primaryAbility: "Destreza",
    weapons:
      "Armas simples, más ballestas de mano, espadas largas, estoques y espadas cortas",
    savingThrows: ["Destreza", "Inteligencia"],
    features: ["Ataque furtivo", "Evasión"],
  },
  {
    name: "Hechicero",
    hitDie: "d6",
    primaryAbility: "Carisma",
    weapons: "Armas simples",
    savingThrows: ["Constitución", "Carisma"],
    features: ["Metamagia", "Orígenes de hechicero"],
  },
  {
    name: "Brujo",
    hitDie: "d8",
    primaryAbility: "Carisma",
    weapons: "Armas simples",
    savingThrows: ["Sabiduría", "Carisma"],
    features: ["Pacto mágico", "Eldritch Invocations"],
  },
  {
    name: "Mago",
    hitDie: "d6",
    primaryAbility: "Inteligencia",
    weapons: "Dagas, dardos, hondas, bastones y ballestas ligeras",
    savingThrows: ["Inteligencia", "Sabiduría"],
    features: ["Lanzamiento de conjuros", "Recuperación arcana"],
  },
];
